"""Demo fixture for ccc: a real ALPHA gate with real inputs.

Scenario. An AI assistant is asked to release a short status summary of a
regulated record. This fixture supplies the check on the requested EPISTEMIC
TRANSITION: before the summary is generated, may the assistant file its summary
under the epistemic status the request names?

POSITION is 'ALPHA', for these reasons, all taken from the library itself:

* ``ccc.cns_connector`` says what CCC judges: "an attempted transition before
  it happens". The judged transitions "evaluate their constitutional rules
  before they change any record, so a refusal means the transition never
  starts. That is the ALPHA end of the CNS gate contract."
* The same module says "CCC has no outcome end: it does not judge a produced
  result on its way out." ``CCCSystem.validate_constitution()`` is a read-only
  report over the whole store and gates nothing, so the connector does not
  present it as an OMEGA gate. ``CccGate.position`` returns
  ``GatePosition.ALPHA`` and ``cns_chain(...).complete()`` is False by design.
* Its candidate is an ``Attempt``: a planned call (an operation plus its
  arguments) that exists before the work does. The gate never sees the
  generated summary, so it could not sit at the OMEGA end even if the demo
  wanted it there.

The candidate this gate judges is therefore the assistant's PLANNED ENTRY for
its summary, built with ``ccc.cns_connector.attempt("ingest", ...)`` and filed
by a MODEL actor under a requested ``EpistemicStatus``. It is handed to
``gate.check(...)`` before the summary is generated.

* ``ok_candidate()``: the planned entry requests status INFERENCE. A model may
  propose, so CCC admits it and the verdict is PASS.
* ``refused_candidate()``: the identical call except that it requests status
  HISTORICAL_RECORD, the status reserved for human-established fact. CCC
  refuses with rule CCC-RATIFICATION-001: "machine-generated material cannot
  be ingested as human-established history/evidence".

REFUSED_OUTCOME is 'TERMINAL_BREACH'. The connector decides RETRY versus
TERMINAL_BREACH by running the same operation, by the same actor, again on a
second scratch copy of the store with the human inputs CCC's rules ask for
added (an authorization basis, a human event, a human-established evidence
root). A model that asks for a human-authority status is still refused, so no
delta repairs it and the verdict is TERMINAL_BREACH, never RETRY. This was
verified by running it (see ``_self_check``), not assumed.

Why ``ingest`` and not ``accept`` or ``classify``. Those name an artifact id,
and CCC makes ids with ``uuid4`` per store, so a zero-argument candidate could
not name an id that exists in a gate built by a separate ``make_gate()`` call.
``ingest`` names none, and its ``epistemic_status`` argument is validated
before anything is stored. This fixture does not exercise CCC's RETRY path
(for example a human ``accept`` with an empty authorization basis); that needs
an artifact id.

The world. ``make_gate()`` builds a fresh ``CCCSystem`` holding the human-
established source record (batch release L-2291, the same record the
governance_gateway fixture uses). The verdicts for ``ingest`` do not depend on
it. It is there so the gate judges inside the demo's world, and so the
self-check can show that judging leaves the live store untouched: the
connector runs every attempt on a scratch copy of the store.

Import safety. Nothing here imports ``cns`` or ``ccc`` when this module loads;
both are imported inside the functions that need them. Without ``cns``
installed, ``make_gate()`` raises ``ccc.cns_connector.CnsNotInstalled`` (an
``ImportError``). The candidate functions need ccc but not cns, because
``attempt`` and ``Attempt`` work either way.

Run as a script for the self-check:  python fixture_ccc.py
"""

from __future__ import annotations

import dataclasses
import json
import sys
from typing import Any

POSITION = "ALPHA"

REFUSED_OUTCOME = "TERMINAL_BREACH"

DESCRIPTION = (
    "Before the summary is written, refuses any request to file the "
    "assistant's machine-generated status summary as human-established "
    "historical record, because CCC lets a model propose but never establish."
)

#: The rule at the front of the reason CCC gives for the refused candidate.
REFUSED_REASON = "CCC-RATIFICATION-001"

_ASSISTANT_ID = "status-summary-assistant"
_ASSISTANT_LABEL = "AI assistant"

_PLANNED_ENTRY = (
    "Status summary of batch release record L-2291, generated by the AI "
    "assistant from the human-established source record."
)
_REQUEST_REASON = "status summary of batch release record L-2291 requested for release"

_SOURCE_RECORD = (
    "Batch release record L-2291, Compound X 10 mg tablets: status released, "
    "reviewed by QA-117 on 2026-09-14."
)


def _regulated_world() -> Any:
    """A new CCCSystem holding the human-established source record."""
    from ccc import Actor, CCCSystem, EpistemicStatus

    system = CCCSystem()
    system.ingest(
        _SOURCE_RECORD,
        actor=Actor.human("qa-reviewer-117", "QA reviewer"),
        epistemic_status=EpistemicStatus.HISTORICAL_RECORD,
        reason="human establishes the regulated source record",
        authorization_basis="QA reviewer sign-off 2026-09-14",
    )
    return system


def make_gate() -> Any:
    """A new, independent ``cns.gate.Gate``: the library's own ``CccGate``.

    Each call builds a fresh ``CCCSystem`` inside a fresh ``CccGate``; no
    instance is cached or shared. Raises ``CnsNotInstalled`` when CNS is absent
    (the connector checks at construction, not on first use).
    """
    from ccc.cns_connector import CccGate

    return CccGate(_regulated_world())


def _planned_entry(status: Any, subject: str) -> Any:
    """The assistant's planned ingest of its summary under ``status``, labelled.

    A new Attempt (and so new argument objects) on every call. Needs no CNS.
    """
    from ccc import Actor
    from ccc.cns_connector import attempt

    planned = attempt(
        "ingest",
        _PLANNED_ENTRY,
        actor=Actor.model(_ASSISTANT_ID, _ASSISTANT_LABEL),
        epistemic_status=status,
        reason=_REQUEST_REASON,
    )
    return dataclasses.replace(planned, subject=subject)


def ok_candidate() -> Any:
    """The planned entry requesting INFERENCE, which CCC admits. Fresh each call."""
    from ccc import EpistemicStatus

    return _planned_entry(
        EpistemicStatus.INFERENCE, "release-summary:file-as-inference"
    )


def refused_candidate() -> Any:
    """The planned entry requesting HISTORICAL_RECORD, which CCC refuses.

    Fresh each call. Identical to ``ok_candidate()`` except for the requested
    status: a model actor asking to file its own output as human-established
    history, which rule CCC-RATIFICATION-001 forbids.
    """
    from ccc import EpistemicStatus

    return _planned_entry(
        EpistemicStatus.HISTORICAL_RECORD,
        "release-summary:file-as-historical-record",
    )


def _check(condition: bool, label: str, failures: list) -> None:
    print(f"  [{'ok' if condition else 'FAIL'}] {label}")
    if not condition:
        failures.append(label)


def _live_state(gate: Any) -> str:
    """The gate's live store as one canonical string, to compare before and after."""
    system = gate._system
    return json.dumps(system.store.snapshot(), sort_keys=True, default=str)


def _self_check() -> int:
    try:
        gate = make_gate()
    except ImportError as exc:  # CnsNotInstalled is an ImportError
        print(f"make_gate() could not run: {type(exc).__name__}: {exc}")
        print("The module imported fine; the gate itself needs cns installed.")
        ok_in, bad_in = ok_candidate(), refused_candidate()
        print(
            "The candidates need only ccc and were built without cns: "
            f"{ok_in.subject!r}, {bad_in.subject!r}"
        )
        return 2

    from ccc.cns_connector import attempt_digest
    from cns.gate import (
        Gate,
        GateChain,
        GateOutcome,
        GatePosition,
        resolve,
        unbound,
    )

    failures: list = []
    print(f"gate name      : {gate.name}")
    print(f"POSITION       : {POSITION} (gate declares {gate.position.name})")
    print(f"REFUSED_OUTCOME: {REFUSED_OUTCOME}")
    print(f"DESCRIPTION    : {DESCRIPTION}")

    before = _live_state(gate)
    ok_in, bad_in = ok_candidate(), refused_candidate()
    ok_res, bad_res = gate.check(ok_in), gate.check(bad_in)
    for label, res in (("ok     ", ok_res), ("refused", bad_res)):
        print(
            f"{label}: position={res.position.name} outcome={res.outcome.name} "
            f"reason={res.reason!r} subject={res.subject!r} "
            f"digest={res.subject_digest[:16]}... bound={res.bound()}"
        )

    print("checks")
    _check(isinstance(gate, Gate), "gate satisfies cns.gate.Gate", failures)
    _check(
        gate.position is GatePosition.ALPHA and gate.position.name == POSITION,
        "POSITION matches the gate's declared position",
        failures,
    )
    _check(
        GateChain(alpha=(gate,)).misplaced() == (),
        "gate sits in the alpha slot",
        failures,
    )
    _check(
        ok_res.outcome is GateOutcome.PASS and ok_res.reason.startswith("admitted"),
        "ok candidate PASSES",
        failures,
    )
    _check(
        bad_res.outcome is GateOutcome[REFUSED_OUTCOME]
        and bad_res.reason.startswith(REFUSED_REASON),
        f"refused candidate gives {REFUSED_OUTCOME} / {REFUSED_REASON}",
        failures,
    )
    _check(
        ok_res.position is GatePosition.ALPHA and bad_res.position is GatePosition.ALPHA,
        "both verdicts carry position ALPHA",
        failures,
    )
    _check(unbound([ok_res, bad_res]) == (), "both verdicts are bound", failures)
    _check(
        ok_res.binds(ok_in.subject, attempt_digest(ok_in))
        and bad_res.binds(bad_in.subject, attempt_digest(bad_in)),
        "each verdict binds to the attempt it judged",
        failures,
    )
    _check(
        not ok_res.binds(bad_in.subject, attempt_digest(bad_in))
        and not bad_res.binds(ok_in.subject, attempt_digest(ok_in)),
        "neither verdict binds to the other attempt",
        failures,
    )
    _check(
        ok_res.subject_digest != bad_res.subject_digest,
        "the two attempts digest differently",
        failures,
    )
    _check(resolve([ok_res]) is GateOutcome.PASS, "resolve([ok]) is PASS", failures)
    _check(
        resolve([ok_res, bad_res]) is GateOutcome[REFUSED_OUTCOME],
        "resolve([ok, refused]) is the refusal outcome",
        failures,
    )
    _check(
        _live_state(gate) == before,
        "judging left the live store exactly as it was",
        failures,
    )
    _check(
        gate.check(ok_in) == ok_res and gate.check(bad_in) == bad_res,
        "re-checking the same attempts gives the same verdicts",
        failures,
    )

    other = make_gate()
    _check(
        other is not gate and other._system is not gate._system,
        "make_gate() twice gives independent gates",
        failures,
    )
    _check(
        other.check(refused_candidate()) == bad_res
        and other.check(ok_candidate()) == ok_res,
        "a second gate, checking in the other order, gives the same verdicts",
        failures,
    )
    a, b = ok_candidate(), ok_candidate()
    _check(
        a is not b
        and a.args is not b.args
        and a.kwargs is not b.kwargs
        and a.content == b.content
        and attempt_digest(a) == attempt_digest(b),
        "ok_candidate() returns a fresh object each call, with equal content",
        failures,
    )
    c, d = refused_candidate(), refused_candidate()
    _check(
        c is not d
        and c.args is not d.args
        and c.kwargs is not d.kwargs
        and c.content == d.content
        and attempt_digest(c) == attempt_digest(d),
        "refused_candidate() returns a fresh object each call, with equal content",
        failures,
    )

    print("PASS" if not failures else f"FAILED: {len(failures)} check(s)")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(_self_check())
